import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <nav className="p-8">
          <Link href="/">Zenblog + NextJS</Link>
        </nav>
        {children}
        <footer className="border-t px-8 py-24">
          Check out{" "}
          <Link className="text-blue-500 underline" href="https://zenblog.com">
            zenblog
          </Link>
        </footer>
      </body>
    </html>
  );
}
