import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex h-screen flex-col"}>
        {/* <nav className="flex gap-1 border-b px-3 py-1 text-sm *:p-2 *:font-medium">
          <h2>Zenblog API</h2>
          <Link href="/">Guides</Link>
          <Link href="/reference">API Reference</Link>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
